#!/usr/bin/lua

local json = require 'jsonc'
local site = require 'gluon.site'
local uci = require('simple-uci').cursor()

-- Create UCI configuration file if not present
local touch_handle = io.popen("touch /etc/config/ffda")
touch_handle:read('*all')
touch_handle:close()

-- Create UCI section
local director_enabled = true
if uci:get("ffda", "director", "enabled") ~= nil then
	director_enabled = uci:get("ffda", "director", "enabled")
end
uci:section('ffda', 'director', 'director', {
	enabled = director_enabled,
})

if site.domain_director.url(nil) ~= nil then
	uci:set("ffda", "director", "url", site.domain_director.url())
end

if site.domain_director.switch_after_offline(nil) ~= nil then
	uci:set("ffda", "director", "switch_after_offline", site.domain_director.switch_after_offline())
end

local urandom = io.open('/dev/urandom', 'r')
local seed1, seed2 = urandom:read(2):byte(1, 2)
math.randomseed(seed1*0x100 + seed2)
urandom:close()

-- Perform domain acquisition at random minute every 3 hours
local minute = math.random(0, 59)

local f = io.open('/usr/lib/micron.d/ffda-domain-director', 'w')
f:write("*/1 * * * *  /usr/bin/ffda-check-gw-reachability\n")
f:write("*/5 * * * *  /usr/bin/ffda-switch-domain\n")
f:write(string.format('%i */3 * * *  /usr/bin/ffda-get-domain\n', minute))
f:close()

uci:commit("ffda")
