#!/usr/bin/lua

local json = require 'jsonc'
local site = assert(json.load('/lib/gluon/site.json'))
local uci = require('simple-uci').cursor()

-- Create UCI configuration file if not present
local touch_handle = io.popen("touch /etc/config/ffda")
touch_handle:read('*all')
touch_handle:close()

-- Create UCI section
uci:section('ffda', 'director', 'director', {
		enabled = site.domain_director.enabled,
		url = site.domain_director.url,
		switch_enabled = site.domain_director.switch_enabled,
		switch_after_offline = site.domain_director.switch_after_offline,
})

uci:commit("ffda")
