#!/usr/bin/lua

local uci = require('simple-uci').cursor()

if uci:get('autoupdater', 'settings', 'branch') ~= 'testing' then
  return
end

local platform_info = require('platform_info')

function Set (list)
  local set = {}
  for _, l in ipairs(list) do set[l] = true end
  return set
end

local update_branch = false

-- These routers were introduced since the last major
-- release, so if you wanted to use them you had to
-- use an experimental image.
local new_models = Set {
  'alfa-network-ap121f',
  'avm-fritz-box-4020',
  'openmesh-a60',
  'tp-link-archer-c25-v1',
  'tp-link-archer-c59-v1',
  'ubiquiti-rocket-m',
  'tp-link-tl-wa901n-nd-v5',
  'raspberry-pi-3',
  'gl-mt300a',
  'gl-mt300n',
  'gl-mt750',
  'netgear-wndr3700v5',
  'zbt-wg3526-16m',
  'zbt-wg3526-32m',
  'a5-v11',
  'd-link-dir-615-h1',
  'd-link-dir-615-d'
}

if new_models[platform_info.get_image_name()] then
  update_branch = true  
  print('[+] device was introduced after latest stable release')
end


if update_branch then
  uci:set('autoupdater', 'settings', 'branch', 'stable')
  uci:save('autoupdater')
  print('[+] autoupdater branch set to stable')
end

