#!/bin/sh

HOSTNAME=$(pretty-hostname)

if [ "$HOSTNAME" = "# 63322-ZA_Dr_Fritz_und_Schroeder" ]; then
    uci delete system.@system[0].pretty_hostname
    uci set system.@system[0].hostname='63322-ZA_Dr_Fritz_und_Schroeder'
fi

